### ISSUE TITLE
RESMP0 problem in Save Mary

### ISSUE THREAD

**Issue by thrust26** [DirtyHairy/stella#22]
The rope is at the left of the crane in the new core, it should be on the right (+3 pixel). The code use RESMP0 to position the rope, so that's most likely the cause of the problem.

Same in Stellarator.

**Comment by DirtyHairy** [comment]
Likely a consequence of #23 .

**Comment by DirtyHairy** [comment]
Fixed in 38d8d89 .

**Comment by sa666666** [comment]
This is still not quite fixed.  Although the rope is now in the correct position, when you move to the extreme left, the rope 'detaches' and is shown in the black area; it should stay attached to the pulley.

**Comment by DirtyHairy** [comment]
Ouch --- overflow :8ball: Fixed in a9d1ed3 .
